### PR TITLE
ve splitting

### PR DESCRIPTION
**Pull request by RadialFinance**
The ve positions are represented as NFTs so that users can buy/sell/transfer these positions. However, protocols building on top of Solidly might be limited in terms of the value they can offer to NFT depositors if these NFTs can only be merged but not split back to enable redemptions. This prevents optionality and locks in users to specific protocols creating monopolies and killing chances of newer experiments in the long-term.

We're making this PR to enable NFT splitting to make the Solidly protocol more flexible as a base layer for others to build on.

### CODE REVIEW

**Comment by paint-swap-finance** [comment]
What happens if the token is listed on a marketplace, someone buys is but is front-run by someone splitting it and reducing the original value? Wonder if the original one should be burnt and 2 new ones created.

Similar things are also possible with `increase_unlock_time`, `merge` and maybe others hmm. Maybe another solution is a function which returns all values like: balance, checkpoint count etc and dapps could query this and display that data atomically and then recall it during calls like sales to make sure they haven't changed.

**Comment by RadialFinance** [comment]
True. Any mutable operation has the potential to be front run in non-atomic flows like marketplaces.

As you say, one approach is to make NFTs immutable and mint/burn as required for mutable operations. This might need more invasive changes in the current contracts, plus requires contracts managing NFTs to properly track mints and burns. 

Another approach is to introduce an NFT "fingerprint" (say, a hash of all relevant data, can be independently verified on the frontend), and add variants of the mutable operations that verify before execution. This puts the onus on marketplaces to properly implement support.

One (little outlandish) idea is to do fingerprints that replace the current sequential token ids which might be cleaner in the long run, but seems like combining the worst of both approaches in terms of contract changes, since it'll also require minting/burning liberally in addition to fingerprints. Not sure if such a fundamental change is desirable at this stage in the project.

Happy to contribute PRs based on your preferences.

**Comment by RobAnon** [comment]
You may be interested in utilizing our already existing FNFT system to fractionalize the NFT you get through Andre into a bunch of 1155 instances for that same purpose. At the very least, it would make sense to encourage adoption of a common interface system if Solidly is going to be offering similar features within its own NFT-subsystem. We use ERC-1155 but the interface we constructed (namely, [IRevest](https://github.com/Revest-Finance/RevestContracts/blob/master/hardhat/contracts/interfaces/IRevest.sol)), already offer nearly all of the same functionality. 

I'm thoroughly in favor of using my own protocol as a wrapper for obvious reasons, but beyond that, I think that if a "split" method is being introduced, we should try to maintain interface parity across different Financial NFT (FNFT) models.

**Comment by 0xwine** [comment]
With the changes proposed here, you can manipulate the gauge votes by moving voting power around multiple NFT and voting.

**Comment by 0xwine** [comment]
With the changes proposed here, you can manipulate the gauge votes by moving voting power around multiple NFT and voting.

https://github.com/andrecronje/solidly/blob/master/contracts/ve.sol#L963

**Comment by RadialFinance** [comment]
Yes, we haven't pulled in changes from _after_ we opened the PR. Waiting on clarity regarding the broader approach before we make further changes.

**Comment by andrecronje** [comment]
Been thinking a lot about this, it *could* work if the original is burned and two new ones are created, but it creates a completely unknown new attack surface, merge works because its essentially an increase_amount with a withdraw wrapped, but decreasing the amounts seem to add a lot of unknown attack vectors. 

So rather, what's the use case for this? It seems like all this does is offer a easy "exit", which isn't exactly a core principal of the system.

Let me know, I'll give it more thought, but given how close we are to launching, I'm hesitant to include this.

**Comment by RadialFinance** [comment]
The primary motivation is to prevent ossification of protocols building on top of Solidly (speaking as one of those protocols that probably _benefits_ from the ossification), especially considering protocols with initial NFTs have a head start in terms of accumulating ve deposits as well as compounding. If a new protocol offering genuinely better terms/UX were to come up, it would have a hard time finding enough SOLID/ve floating outside of the initial few protocols.

While we agree that its an exit from protocols building on top of Solidly, its important to note that its not an exit from Solidly itself - the exiters still have only ve that's likely locked up for years. On the other hand, having the option for an exit would foster competition among protocols building on top of Solidly which can only be good for the ecosystem as a whole.

Completely agree with the last part though, maybe it _is_ too late to add this in, will leave it to your judgement.

**Pull request closed without merging**
